version: "3.7"
services:
  web-app: 
    build: .

  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    command:
      - --http-address
      - 0.0.0.0:3000
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://web-app:3000/ 
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: demo
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_ENCODE_STATE: false 
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true 
      OAUTH2_PROXY_EMAIL_DOMAINS: '*' 
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:3000/oauth2/callback 
      OAUTH2_PROXY_COOKIE_SECRET: ${COOKIE_SECRET} 

    ports:
      - 3000:3000 
